# Generated by Django 4.0.4 on 2022-04-28 11:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250, verbose_name='Username')),
                ('message', models.TextField(max_length=50, verbose_name='Tweet')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 4, 28, 11, 56, 46, 804053, tzinfo=utc), verbose_name='Tweet Date')),
            ],
        ),
    ]
